/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Ball(props) {
  const { nodes, materials } = useGLTF("./models/ball.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.TTBall}
        position={[-0.46174, 2.43609, -0.25688]}
        scale={0.06441}
      />
    </group>
  );
}

useGLTF.preload("./models/ball.glb");
