/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CutBall(props) {
  const { nodes, materials } = useGLTF("./models/ballprinting.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.46174, 2.43609, -0.2528]} scale={0.06441}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001.geometry}
          material={materials["TTBall.001"]}
        />
        <mesh
          castShadowas
          receiveShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials["TTBall.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/ballprinting.glb");
