/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function HeroText(props) {
  const textRef = useRef()

  useFrame((state) => {
    textRef.current.position.y = 0.006*Math.sin(state.clock.getElapsedTime()*1.5)
    textRef.current.rotation.x = 0.001*Math.cos(state.clock.getElapsedTime()*0.75)
    textRef.current.rotation.y = 0.001*Math.cos(state.clock.getElapsedTime()*0.75)
  })

  const { nodes, materials } = useGLTF("./models/herotext.glb");
  return (
    <group ref={ textRef } dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LT.geometry}
        material={materials["Text.001"]}
        position={[-2.67827, 2.71678, 0.08841]}
        rotation={[Math.PI / 2, 0, -0.22726]}
        scale={0.14217}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EP.geometry}
        material={materials["Text.001"]}
        position={[-2.68827, 2.91497, 0.08841]}
        rotation={[Math.PI / 2, 0, -0.22726]}
        scale={0.24303}
      />
    </group>
  );
}

useGLTF.preload("./models/herotext.glb");
