/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function HeroText(props) {
  const { nodes, materials } = useGLTF("./models/herotext.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.Material}
        position={[-3.09, 2.91, 0.48]}
        rotation={[Math.PI / 2, 0, -0.22]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials.Material}
        position={[-3.09, 2.72, 0.48]}
        rotation={[Math.PI / 2, 0, -0.22]}
        scale={0.17}
      />
    </group>
  );
}

useGLTF.preload("./models/herotext.glb");
