/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Printer(props) {
  const { nodes, materials } = useGLTF("./models/printer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.TTBall}
        position={[-0.46, 2.44, -0.02]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Printer_Frame.geometry}
        material={materials["Printer Frame"]}
        position={[-0.56, 2.22, -0.47]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Printer_Bed.geometry}
        material={materials.Bed}
        position={[-0.46, 2.36, -0.02]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ZRod.geometry}
        material={materials["Stainless.001"]}
        position={[-0.89, 3.17, -0.02]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.01, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XAxisEnds.geometry}
        material={materials.Caps}
        position={[-0.88, 2.63, -0.02]}
      />
      <group position={[-0.46, 2.62, -0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.nozzle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Stainless.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.YAxisCap.geometry}
        material={materials.Caps}
        position={[-0.46, 2.33, -0.36]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.05, 0.06, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XAxisRods.geometry}
        material={materials["Stainless.001"]}
        position={[-0.88, 2.63, -0.02]}
        scale={[0.05, 0.06, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.YAxisRods.geometry}
        material={materials["Stainless.001"]}
        position={[-0.46, 2.33, -0.36]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.05, 0.06, 0.05]}
      />
    </group>
  );
}

useGLTF.preload("./models/printer.glb");
