/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export default function PrinterNozzle(props) {

  const defaultXPos = -0.46193
  const defaultYPos = 2.62214
  const [position, setPosition] = useState(defaultXPos)

  // Animation
  useFrame((state) => {
    // console.log(state.camera)
    setPosition(defaultXPos + 0.059*Math.sin(state.clock.getElapsedTime()))
  })

  const { nodes, materials } = useGLTF("./models/printernozzle.glb");
  return (
    <group dispose={null}>
      <group position={ [props.animate ? position : defaultXPos, 2.62214, -0.25576] }>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.nozzle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Stainless.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/printernozzle.glb");
