/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PrinterXAxis(props) {
  const { nodes, materials } = useGLTF("./models/printerxaxis.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XAxisEnds.geometry}
        material={materials.Caps}
        position={[-0.88, 2.63, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XAxisRods.geometry}
        material={materials["Stainless.001"]}
        position={[-0.88, 2.63, -0.02]}
        scale={[0.05, 0.06, 0.05]}
      />
    </group>
  );
}

useGLTF.preload("./models/printerxaxis.glb");
