/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PrinterBed(props) {
  const { nodes, materials } = useGLTF("./models/printerbed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Printer_Bed.geometry}
        material={materials.Bed}
        position={[-0.46, 2.36, -0.02]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.38}
      />
    </group>
  );
}

useGLTF.preload("./models/printerbed.glb");
