/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PrinterNozzle(props) {
  const { nodes, materials } = useGLTF("./models/printernozzle.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.46, 2.62, -0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.nozzle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Stainless.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/printernozzle.glb");
