/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Scene(props) {
  const { nodes, materials } = useGLTF("./models/workshop.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.TTBall}
        position={[-0.462, 2.436, -0.019]}
        scale={0.064}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PIP.geometry}
        material={materials["Glowing Text"]}
        position={[-0.89, 2.208, 0.388]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.034}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RC_Rod_End_M3_v2_Low_Res.geometry}
        material={materials["Stainless.001"]}
        position={[-1.61, 2.152, 0.345]}
        rotation={[1.059, 0, 1.161]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RC_Rod_End_M3_v2_Low_Res001.geometry}
        material={materials["Stainless.001"]}
        position={[-1.576, 2.152, 0.242]}
        rotation={[1.475, 0.504, -0.213]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Clamp_V2_Low_Res.geometry}
        material={materials.Clamp}
        position={[-1.679, 2.176, 0.124]}
        rotation={[-Math.PI, 0.375, 0]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.M3_Bottom.geometry}
        material={materials["Stainless.001"]}
        position={[-1.684, 2.147, 0.383]}
        rotation={[0, -0.962, -0.116]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.M3_Bottom001.geometry}
        material={materials["Stainless.001"]}
        position={[-1.73, 2.147, 0.395]}
        rotation={[-Math.PI, -0.639, 3.026]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.M3_Bottom002.geometry}
        material={materials["Stainless.001"]}
        position={[-1.724, 2.147, 0.334]}
        rotation={[Math.PI, -1.066, 3.026]}
        scale={0.003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Aluminium_25T_Servo_Horn_v2.geometry}
        material={materials["Stainless.001"]}
        position={[-1.827, 2.152, 0.52]}
        rotation={[0, -0.898, Math.PI]}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.Material}
        position={[-3.089, 2.915, 0.477]}
        rotation={[Math.PI / 2, 0, -0.219]}
        scale={0.273}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials.Material}
        position={[-3.089, 2.717, 0.477]}
        rotation={[Math.PI / 2, 0, -0.219]}
        scale={0.172}
      />
      <group position={[-0.267, 2.005, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.Bench}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Printer Frame"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Printer_Frame.geometry}
        material={materials["Printer Frame"]}
        position={[-0.559, 2.218, -0.466]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Printer_Bed.geometry}
        material={materials.Bed}
        
        position={[-0.462, 2.359, -0.017]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.385}
        />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ZRod.geometry}
        material={materials["Stainless.001"]}
        position={[-0.89, 3.169, -0.018]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.014, 0.02, 0.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XAxisEnds.geometry}
        material={materials.Caps}
        position={[-0.883, 2.629, -0.018]}
      />
      <group position={[-0.462, 2.622, -0.018]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.nozzle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Stainless.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.YAxisCap.geometry}
        material={materials.Caps}
        position={[-0.461, 2.326, -0.364]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.051, 0.064, 0.051]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XAxisRods.geometry}
        material={materials["Stainless.001"]}
        position={[-0.883, 2.629, -0.018]}
        scale={[0.051, 0.064, 0.051]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.YAxisRods.geometry}
        material={materials["Stainless.001"]}
        position={[-0.461, 2.326, -0.364]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.051, 0.064, 0.051]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Drawing}
        position={[-2.278, 2.14, 0.174]}
        rotation={[0, 0.562, 0]}
        scale={[0.45, 0.316, 0.316]}
      />
      <group
        position={[-0.065, 2.482, -1.35]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[8.769, 3.051, 3.051]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials.Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.concrete_floor_worn_001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/workshop.glb");
